### test request get
GET http://localhost:3000/api HTTP/1.1

### create user
POST {{ BASE_URL }}/users HTTP/1.1
content-type: application/json

{
  "name": "Husni Mubarok 2",
  "userName": "husni2",
  "password": "1234",
  "confirmPassword": "1234",
  "role": "admin"
}

### user login
POST {{ BASE_URL }}/users/login
content-type: application/json
{
  "userName": "husnie",
  "password": "1234"
}

{{
  $global.accessToken=JSON.parse(response.body).accessToken;
  $global.refreshToken=JSON.parse(response.body).refreshToken;
}}

### update user
PUT {{ BASE_URL }}/users/1
content-type: application/json
Authorization: Bearer {{$global.accessToken}}
{
  "name": "Husni Mubarok",
  "userName": "husnie",
  "password": "1234",
  "confirmPassword": "1234",
  "role": "admin"
}

### delete user
DELETE {{ BASE_URL }}/users/2
content-type: application/json
Authorization: Bearer {{$global.accessToken}}

### get all user
GET {{ BASE_URL }}/users
Authorization: Bearer {{$global.accessToken}}

### get user by Id
GET {{ BASE_URL }}/users/1
Authorization: Bearer {{$global.accessToken}}

### refresh token
GET {{ BASE_URL }}/users/refresh
Authorization: Bearer {{$global.refreshToken}}

{{
  $global.accessToken=JSON.parse(response.body).accessToken;
  $global.refreshToken=JSON.parse(response.body).refreshToken;
}}